{% set name = "envier" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/envier-{{ version }}.tar.gz
  sha256: f35ca8605f0c70c2c0367133af9dc1ef16710021dbd0e28c1b0a83070db06768

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools-scm
    - pip
  run:
    - python >=3.6

test:
  imports:
    - envier
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DataDog/envier
  summary: Python application configuration via the environment
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aymondebroglie
